/*
 * THIS FILE IS AUTOMATICALLY GENERATED BY gen_scrn_dispatch.pl
 * DO NOT EDIT!!
 */
#ifndef __glxlibglvnd_dispatchindex_h__
#define __glxlibglvnd_dispatchindex_h__

typedef enum __GLXdispatchIndex {
    DI_BindTexImageEXT,
    DI_ChooseFBConfig,
    // ChooseVisual implemented by libglvnd
    // CopyContext implemented by libglvnd
    // CreateContext implemented by libglvnd
    DI_CreateContextAttribsARB,
    // CreateGLXPixmap implemented by libglvnd
    // CreateNewContext implemented by libglvnd
    // CreatePbuffer implemented by libglvnd
    // CreatePixmap implemented by libglvnd
    // CreateWindow implemented by libglvnd
    // DestroyContext implemented by libglvnd
    // DestroyGLXPixmap implemented by libglvnd
    // DestroyPbuffer implemented by libglvnd
    // DestroyPixmap implemented by libglvnd
    // DestroyWindow implemented by libglvnd
    // FreeContextEXT implemented by libglvnd
    // GetClientString implemented by libglvnd
    // GetConfig implemented by libglvnd
    DI_GetContextIDEXT,
    // GetCurrentContext implemented by libglvnd
    // GetCurrentDisplay implemented by libglvnd
    DI_GetCurrentDisplayEXT,
    // GetCurrentDrawable implemented by libglvnd
    // GetCurrentReadDrawable implemented by libglvnd
    DI_GetDriverConfig,
    // GetFBConfigAttrib implemented by libglvnd
    // GetFBConfigs implemented by libglvnd
    // GetProcAddress implemented by libglvnd
    // GetProcAddressARB implemented by libglvnd
    DI_GetScreenDriver,
    // GetSelectedEvent implemented by libglvnd
    // GetVisualFromFBConfig implemented by libglvnd
    // ImportContextEXT implemented by libglvnd
    // IsDirect implemented by libglvnd
    // MakeContextCurrent implemented by libglvnd
    // MakeCurrent implemented by libglvnd
    // QueryContext implemented by libglvnd
    DI_QueryContextInfoEXT,
    // QueryDrawable implemented by libglvnd
    // QueryExtension implemented by libglvnd
    // QueryExtensionsString implemented by libglvnd
    // QueryServerString implemented by libglvnd
    // QueryVersion implemented by libglvnd
    DI_ReleaseTexImageEXT,
    // SelectEvent implemented by libglvnd
    // SwapBuffers implemented by libglvnd
    DI_SwapIntervalEXT,
    // UseXFont implemented by libglvnd
    // WaitGL implemented by libglvnd
    // WaitX implemented by libglvnd
    DI_LAST_INDEX
} __GLXdispatchIndex;

#endif // __glxlibglvnd_dispatchindex_h__
